### ISSUE TITLE
Dibsfw - payment currency issue

### ISSUE THREAD

**Issue by unicoder88** [DIBS-Payment-Services/Magento#12]
Good day!
We discovered a bug in current Dibsfw version 3.2.2. It results in invoice not capturing onine in some setups.

## Steps to reproduce:

- configure base store currency NOK
- create product, set price 50 NOK
- create English store view, currency USD, set up currency rate - System > Manage Currency > Rates
- as a customer, switch to English store view, and add the product to cart. Price will be displayed as $7.
- pay using Dibs - paid $7 in USD
- as admin, try to invoice the order
- get error "DIBS returned DECLINE check your payment in DIBS admin. Error msg: 7."

## Reason:

- When redirecting to DIBS payment, order details are sent in *display currency* and amount, e.g. 7 USD.
>  dibs_fw_api::dibsflex_api_requestModel -> dibsflex_api_applyCommon
> amount = info.order.total = order.total_due (see dibs_fw_helpers::dibsflex_helper_getOrderObj)
> currency = info.order.currency = order.order_currency_code

- However, when Magento calls Dibsfw.capture(payment, amount), amount is given in *base currency*, 50 NOK in our example. For DIBS this looks like capturing of 50 USD and it fails with error 7 - Amount too high according to http://tech.dibspayment.com/D2/API/Error_codes

## Possible solutions:

- always pay in base currency - this is default Magento way (see PayPal), but might not be appropriate
- in capture(), refund() etc. convert given base amount to display amount using currency rate stored in order.

Looking forward to you comments.

**Comment by maxwhite** [comment]
Hi, thanks for report. We will look at this asap and get back to you

**Comment by mladenilic** [comment]
Any news here?

**Comment by maxwhite** [comment]
Hi, it was fixed with this commit :
https://github.com/DIBS-Payment-Services/Magento/commit/9adac063ae1ce98de0087dc2d285056a1c1a9bcd
