### ISSUE TITLE
Missing Timeout.php for PW module

### ISSUE THREAD

**Issue by SchneiderA** [DIBS-Payment-Services/Magento#15]
After installing PW module I'm presented with a php warning for a missing file:
`Dibspw/Dibspw/Model/System/Config/Source/Timeout.php`

This file only seems to exist for your FW module, but the PW module specifically asks for it's own file in system.xml line 147.
`<source_model>dibspw/system_config_source_timeout</source_model>`

**Comment by sprankhub** [comment]
This is fixed with https://github.com/DIBS-Payment-Services/Magento/commit/cfd59ad716109e3b7a42b0f82106d33ec0f5186b.
