### ISSUE TITLE
Error in callback to magento

### ISSUE THREAD

**Issue by batterigiganten** [DIBS-Payment-Services/Magento#9]
We use DX module for Dibs, and we have trouble with callback it tries to call this url  https://batterigiganten.no/Dibspw/Dibspw/callback/ 

Please contact me as soon as possible, it starts to be urgent.

**Comment by maxwhite** [comment]
Hi, could you please describe the problem you have in more detail step by step

**Comment by batterigiganten** [comment]
I will try to describe.

When a customer place order and pay with Dibs by using the DX module for magento, the order are placed after fulfill payment, but the payment details from dibs are not transferred, and seem like the API connection is not working. we can not aktivate the invoice from magento only by manually aktivate in admin.dibs...  

My email are tore@batterigiganten.no, if you want you can remote my computer for aksess the server?

**Comment by batterigiganten** [comment]
did you recieve my email? i got an error on your emailadress?

**Comment by maxwhite** [comment]
No, try to send to this email:
maksim.belov@dibs.com.ua

**Comment by MarySmith13** [comment]
Hi! Have you solved this problem? I hope Magento has improved their finance aspects for 3 years and there is no problems like this now. I know not bad developers ( http://magecom.net/ ) working on magento's platform and I'm gonna to use their services for building online stores. I hope I won't face with this kind of problem.
